name: Run Azure Load Test

on:
  workflow_dispatch:

jobs:

  loadTest:
    name: Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v3
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
        
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtest-config.yaml'
          loadTestResource: ${{ secrets.AZURE_LOADTEST_RESOURCE }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
